ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks
        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    submodules: false


repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        exclude:  docs
      - id: check-added-large-files
        args: ['--maxkb=100000']
      - id: end-of-file-fixer
        exclude: docs
      - id: check-yaml
        args: ["--unsafe"]


  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Fixes formatting
        language_version: python3
        args: ["--line-length=120"]



  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Checks pep8 style
        args: [
          "--max-line-length=120",
          # Ignore imports in init files
          "--per-file-ignores=
            */__init__.py:F401,setup.py:E121,*/test_jnbs/props/euler_scripts/*.py:F401 E722 E711 E266,
            ",
          # ignore long comments (E501), as long lines are formatted by black
          # ignore Whitespace before ':' (E203)
          # ignore lambdas (E731)
          # ignore Line break occurred before a binary operator (W503)
          # needed to not remove * imports (for example in _all_blocks.py)
          "--ignore=E501,E203,E231,E731,W503,F405",
        ]

  - repo: local
    hooks:
      - id: jupyisort
        name: Sorts ipynb imports
        entry: jupytext --pipe-fmt ".py" --pipe "isort - --multi-line=3 --trailing-comma --force-grid-wrap=0 --use-parentheses --line-width=99" --sync
        files: \.ipynb$
        language: python
        stages: [push]

      - id: jupyblack
        name: Fixes ipynb format
        entry: jupytext --pipe-fmt ".py" --pipe "black - --line-length=120" --sync
        files: \.ipynb$
        language: python
        stages: [push]
